import "./style.css"


export const metadata = {
  title: 'authApp',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children,}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
